# Generated by Django 5.2.6 on 2025-10-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='last_modified',
        ),
    ]
